import java.io.BufferedReader; 
import java.io.BufferedWriter;
import java.io.FileReader;
import java.util.Arrays; // Arrays 임포트 추가
import java.io.FileWriter; // alert창 import
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JCheckBox;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author migyu
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("회원가입 모듈");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnMember = new javax.swing.ButtonGroup();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        pswPW = new javax.swing.JPasswordField();
        pswCheck = new javax.swing.JPasswordField();
        lblPW = new javax.swing.JLabel();
        lblCheck = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblMember = new javax.swing.JLabel();
        lblBobby = new javax.swing.JLabel();
        rbtnMember = new javax.swing.JRadioButton();
        rbtnNoMember = new javax.swing.JRadioButton();
        rbtnStudent = new javax.swing.JRadioButton();
        chbTennis = new javax.swing.JCheckBox();
        chbGolf = new javax.swing.JCheckBox();
        chbGame = new javax.swing.JCheckBox();
        chbSwim = new javax.swing.JCheckBox();
        chbBook = new javax.swing.JCheckBox();
        btnCheck = new javax.swing.JButton();
        chbSki = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblID.setText("아이디");

        lblName.setText("성 명");

        pswCheck.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswCheckKeyTyped(evt);
            }
        });

        lblPW.setText("비밀번호");

        lblCheck.setText("비밀번호 확인");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("맑은 고딕", 1, 18)); // NOI18N
        jLabel5.setText("회원 가입");

        jButton1.setText("회원 가입");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblMember.setText("회원 구분");

        lblBobby.setText("관심 분야");

        BtnMember.add(rbtnMember);
        rbtnMember.setText("정회원");

        BtnMember.add(rbtnNoMember);
        rbtnNoMember.setText("준회원");

        BtnMember.add(rbtnStudent);
        rbtnStudent.setText("학생회원");

        chbTennis.setText("테니스");

        chbGolf.setText("골프");

        chbGame.setText("게임");

        chbSwim.setText("수영");

        chbBook.setText("독서");

        btnCheck.setText("중복 확인");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        chbSki.setText("스키");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel5)
                .addGap(0, 168, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCheck)
                                .addComponent(lblPW)
                                .addComponent(lblName)
                                .addComponent(lblID))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pswCheck)
                                .addComponent(pswPW)
                                .addComponent(txtName)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheck))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblMember)
                                .addComponent(lblBobby))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chbSwim)
                                        .addComponent(chbSki))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chbBook)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(chbGame)
                                            .addGap(18, 18, 18)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chbTennis)
                                        .addComponent(chbGolf)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(rbtnMember)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnNoMember)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnStudent)))
                            .addGap(84, 84, 84))))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCheck))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPW))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCheck))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMember)
                        .addComponent(rbtnMember))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnNoMember)
                        .addComponent(rbtnStudent)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBobby)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chbSwim)
                        .addGap(18, 18, 18)
                        .addComponent(chbSki))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbGame)
                            .addComponent(chbGolf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chbBook)
                            .addComponent(chbTennis))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = txtID.getText();
        char[] passwd = pswPW.getPassword();
        char[] pwCheck = pswCheck.getPassword();
        String name = txtName.getText();
        
        Map<JCheckBox, Integer> checkboxWeights = new HashMap<>();
        checkboxWeights.put(chbTennis, 1);
        checkboxWeights.put(chbBook, 2);
        checkboxWeights.put(chbSki, 4);
        checkboxWeights.put(chbGolf, 8);
        checkboxWeights.put(chbGame, 16);
        checkboxWeights.put(chbSwim, 32);
        
        
        if (id.isEmpty() || passwd.length == 0 || pwCheck.length == 0 || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "모든 칸을 기입하여 주세요.", "가입 처리 거절", JOptionPane.ERROR_MESSAGE); 
            return;
        }
   
        
        if (Arrays.equals(passwd, pwCheck)) {
            if (!isIdDuplicate(id)) {   
                try (BufferedWriter writer = new BufferedWriter(new FileWriter("member.txt", true))) {
                    writer.write(id + " ");
                    writer.write(new String(passwd) + " ");
                    writer.write(name + " ");
                    if(rbtnMember.isSelected())
                        writer.write("정회원 ");
                    else if(rbtnNoMember.isSelected())
                        writer.write("준회원 ");
                    else if(rbtnStudent.isSelected())
                        writer.write("학생회원 ");
                    
                    int interestFileds = 0;
                    for (Map.Entry<JCheckBox, Integer> entry : checkboxWeights.entrySet()){
                        JCheckBox checkBox = entry.getKey();
                        if (checkBox.isSelected()) {
                            interestFileds += entry.getValue();
                        }
                    }
                    writer.write(Integer.toString(interestFileds));
                    writer.newLine();
                    
                    writer.flush(); 
                    JOptionPane.showMessageDialog(null, "가입 처리가 완료되었습니다.", "가입 성공", JOptionPane.INFORMATION_MESSAGE);
                
                    txtID.setText("");
                    pswPW.setText("");
                    pswCheck.setText("");
                    txtName.setText("");
                    BtnMember.clearSelection();
                    chbBook.setSelected(false);
                    chbGame.setSelected(false);
                    chbGolf.setSelected(false);
                    chbSki.setSelected(false);
                    chbSwim.setSelected(false);
                    chbTennis.setSelected(false);
                } catch (IOException e){
                    e.printStackTrace();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "존재하는 아이디입니다. 다른 아이디로 가입하세요.", "가입 처리 거절", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            String message = "비밀번호가 일치하지 않습니다.";
            JOptionPane.showMessageDialog(null, message, "가입 처리 거절", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed

        
        String id = txtID.getText();
        
            
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "아이디를 입력하세요.", "입력 필요", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        if (isIdDuplicate(id)) {
            String message = "이미 존재하는 아이디입니다.";
            JOptionPane.showMessageDialog(null, message, "중복 확인 결과", JOptionPane.ERROR_MESSAGE);
        } else {
            String message = "사용가능한 아이디입니다.";
            JOptionPane.showMessageDialog(null, message, "중복 확인 결과", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void pswCheckKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswCheckKeyTyped
        // 비밀번호 확인란에 비밀번호를 채우고 엔터를 누르면 비밀번호가 같은지 확인
        // 취소 (회원가입 버튼을 누르는 과정에서 확인하기로 함)
        
        
        
        
        
    }//GEN-LAST:event_pswCheckKeyTyped
    private boolean isIdDuplicate(String id){
        
        
        
        try (BufferedReader reader = new BufferedReader(new FileReader("member.txt"))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(" ");
                if (parts.length >= 1 && parts[0].equals(id)){
                    return true;
                }
            }
        } catch (IOException e) {
           
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnMember;
    private javax.swing.JButton btnCheck;
    private javax.swing.JCheckBox chbBook;
    private javax.swing.JCheckBox chbGame;
    private javax.swing.JCheckBox chbGolf;
    private javax.swing.JCheckBox chbSki;
    private javax.swing.JCheckBox chbSwim;
    private javax.swing.JCheckBox chbTennis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblBobby;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblMember;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPW;
    private javax.swing.JPasswordField pswCheck;
    private javax.swing.JPasswordField pswPW;
    private javax.swing.JRadioButton rbtnMember;
    private javax.swing.JRadioButton rbtnNoMember;
    private javax.swing.JRadioButton rbtnStudent;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
